data_dir = ""
attachment_send = ""
language = "zh"

[[projects]]
  name = "SPLLM"

  [projects.agent]
    type = "codex"
    provider = "openai"

    [projects.agent.options]
      mode = "suggest"
      work_dir = "E:\\SPLLM"

    [[projects.agent.providers]]
      name = "openai"
      api_key = "${OPENAI_API_KEY}"

    [[projects.agent.providers]]
      name = "sensenova"
      api_key = "sk-VOUWVPyyuaZUvjkFqDSxQVu6QCdIqdV8"
      base_url = "https://token.sensenova.cn/v1"
      model = "deepseek-v4-flash"

    [[projects.agent.providers]]
      name = "shusheng"
      api_key = "sk-jJZHe9hE5v9vZnf8oWkoeamupO24XturfmU7nqjCIPzLfUOI"
      base_url = "https://chat.intern-ai.org.cn/api"
      model = "intern-latest"

  [[projects.platforms]]
    type = "weixin"

    [projects.platforms.options]
      account_id = "7a1097abd622@im.bot"
      allow_from = "*"
      token = "7a1097abd622@im.bot:060000b0bf44c100aef3159613cf239c973008"
      base_url = "https://ilinkai.weixin.qq.com"

[log]
  level = "info"

[speech]
  enabled = false
  provider = ""
  language = ""

  [speech.openai]
    api_key = ""
    base_url = ""
    model = ""

  [speech.groq]
    api_key = ""
    model = ""

  [speech.qwen]
    api_key = ""
    base_url = ""
    model = ""

  [speech.gemini]
    api_key = ""
    model = ""

[tts]
  enabled = false
  provider = ""
  voice = ""
  tts_mode = ""
  max_text_len = 0

  [tts.openai]
    api_key = ""
    base_url = ""
    model = ""

  [tts.qwen]
    api_key = ""
    base_url = ""
    model = ""

  [tts.minimax]
    api_key = ""
    base_url = ""
    model = ""

[cron]
  session_mode = ""

[webhook]
  port = 0

[bridge]
  port = 0

[management]
  port = 0
